# Generated by Django 3.2.16 on 2023-01-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='object_id',
            field=models.CharField(db_index=True, max_length=191),
        ),
    ]
